TheEadie/WormsLeague

appveyor.yml
Publish to GitHub on merge to master
=> Continuous wormage

Uber Coolest Options.txt
=> Reduce girders to 1 Ammo

Uber Coolest Options.txt
Makes mole bombs much more powerful so they are actually useful. (See table from http://worms2d.info/Mole_Bomb)
Power	Maximum injury	Crater diameter
11	15 hp	35 px
12	21	47
1	24	47
2	27	61
3	30	61
4	33	61
5	36	73
19	39	73
14	45	85
15	60	123
=> Make mole bombs crazy powerful

Uber Coolest Options.txt
See: https://redgate.slack.com/archives/games-worms/p1476275310000555
=> Remove jet pack

CreateGifs.ps1
Lets have this in the main repo rather than just as a gist somewhere
=> Add the helper functions as a script for creating gifs

Uber Coolest Options.txt
=> Move baseball bat earlier

HostWormsGame.ps1, README.md
My laptop has two physical adapters (ethernet and wifi). This PR picks the fastest *connected* physical adapter. Works on my machine ;-)
=> Get the right IP address with multiple adapters

WormsGifTool/GifTool/CreateGifControl.xaml, WormsGifTool/GifTool/CreateGifControl.xaml.cs, WormsGifTool/GifTool/ViewModel/CreateGifViewModel.cs, WormsGifTool/GifTool/ViewModel/SelectTurnViewModel.cs
- Removes some validation that made it difficult to type into timestamp fields
- Fixes a crash that prevented loading a game in which a player completed their turn without using a weapon
- Fixes a nullref elsewhere in the code
=> A few minor fixes to the GIF tool

Schemes/.build/build.ps1, Schemes/Christmas 2019.txt
Based on Andy's proposed changes for next year
=> Create scheme for xmas tournament

CommandLine/GitVersion.yml, CommandLine/src/CliModule.cs, CommandLine/src/Commands/Root.cs, CommandLine/src/Commands/Setup.cs, CommandLine/src/Commands/Update.cs, CommandLine/src/Components/ComponentsRepository.cs, CommandLine/src/Components/Updaters/GitHubReleaseUpdater/GitHubReleaseUpdateConfig.cs, CommandLine/src/Components/Updaters/GitHubReleaseUpdater/GitHubReleaseUpdater.cs, CommandLine/src/Configuration/Config.cs, CommandLine/src/Configuration/ConfigManager.cs, CommandLine/src/Configuration/SecureStorage/ICredentialStorage.cs, CommandLine/src/Configuration/SecureStorage/WindowsCredentialStorage.cs, CommandLine/src/Updates/PackageManagers/GitHubReleasesRepository.cs, CommandLine/src/worms.csproj
- Adds a new verb to the command line to provide interactive setup.
- Stores a users PAT token for GitHub to allow working around #54
=> CLI - Setup command

CommandLine/src/Commands/Update.cs, CommandLine/src/Components/Component.cs, CommandLine/src/Components/ComponentsRepository.cs, InstallCli.ps1
Also fixes an issue where update would fail.
=> CLI - Add logging to Update command

CommandLine/Install.ps1
=> Add new line before PS profile alias

CommandLine/src/Commands/Host.cs
This fixes an issue with using the host command when connected to a network using VPN.
=> Host IP - Find network adapter for the league's domain

CommandLine/src/Commands/GetScheme.cs, CommandLine/src/Logging/DefaultSchemesPrinter.cs, CommandLine/src/Logging/IResourcePrinter.cs, CommandLine/src/Logging/TableOutput/Table.cs, CommandLine/src/Logging/TableOutput/TableBuilder.cs, CommandLine/src/Logging/TableOutput/TableColumn.cs, CommandLine/src/Logging/TableOutput/TablePrinter.cs
Adds columns:
- (Starting) Health
- Turn time
- Round time
- Worms select
- Weapons with at least 1 ammo
Also truncates the table if its bigger than the console window.
=> Show more columns on "get schemes"

.github/workflows/build-cli.yml, CommandLine/.build/private/calculate-version.sh, CommandLine/.build/private/dotnet.sh, CommandLine/.build/private/logging.sh, CommandLine/.build/private/publish.sh, CommandLine/.build/publish.sh, CommandLine/makefile
- Show output from command when gitversion fails (Hack due to gitversion not using stderr for logging)
- Build to platform-specific output directories
=> Build improvements

.github/workflows/build-cli.yml, CommandLine/.build/private/calculate-version.sh, CommandLine/.build/private/release-github.sh, CommandLine/.build/release.sh, CommandLine/makefile
- Add release tasks to `make`
- Add logging to match build tasks
=> Improve logging in release

CommandLine/GitVersion.yml, CommandLine/src/Resources/Schemes/Text/SchemeTextReader.cs, CommandLine/src/Resources/Schemes/Text/SchemeTextWriter.cs
Adds support for the new features in Scheme format V3 as documented on https://worms2d.info/Game_scheme_file
=> Scheme V3 support

.github/workflows/cli.yml, CommandLine/.build/dockerfile, CommandLine/GitVersion.yml, CommandLine/src/WormsArmageddon/Windows/WormsLocator.cs, CommandLine/src/worms.csproj
Updates the CLI to run using .net5.0
=> CLI - Net 5.0

.github/workflows/gif-tool.yml, WormsGifTool/.build/build.ps1, WormsGifTool/GifTool.Tests/GifTool.Tests.csproj, WormsGifTool/GifTool/App.config, WormsGifTool/GifTool/GifTool.csproj, WormsGifTool/GitVersion.yml
Update the Gif Tool to use .NET 5
=> .NET 5 Gif Tool

CommandLine/GitVersion.yml, CommandLine/src/Commands/Resources/Delete.cs, CommandLine/src/Commands/Resources/Replays/DeleteReplay.cs, CommandLine/src/Commands/Resources/Replays/ProcessReplay.cs, CommandLine/src/Commands/Resources/Replays/ViewReplay.cs, CommandLine/src/Commands/Resources/Schemes/DeleteScheme.cs, CommandLine/src/Commands/Resources/View.cs, CommandLine/src/Commands/Root.cs, CommandLine/src/Container/CliModule.cs, CommandLine/src/Resources/IResourceDeleter.cs, CommandLine/src/Resources/Replays/LocalReplayDeleter.cs, CommandLine/src/Resources/Replays/LocalReplayRetriever.cs, CommandLine/src/Resources/ResourceDeleter.cs, CommandLine/src/Resources/Schemes/LocalSchemeDeleter.cs, CommandLine/src/WormsArmageddon/Replays/IReplayLocator.cs, CommandLine/src/WormsArmageddon/Replays/IReplayPlayer.cs, CommandLine/src/WormsArmageddon/Replays/ReplayLocator.cs, CommandLine/src/WormsArmageddon/Replays/ReplayPaths.cs, CommandLine/src/WormsArmageddon/Replays/ReplayPlayer.cs
Adds new commands:
- `worms view replay <name>`
- `worms delete replay <name>`
=> View and delete replays

CommandLine/.editorconfig, CommandLine/src/Worms.Armageddon.Game/GameInfo.cs, CommandLine/src/Worms.Armageddon.Game/Replays/ReplayPaths.cs, CommandLine/src/Worms.Armageddon.Resources.Tests/Replays/ReplayTextReaderShould.cs, CommandLine/src/Worms.Armageddon.Resources/Modules/ArmageddonResourcesModule.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/ReplayResource.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/ReplayResourceBuilder.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/IReplayLineParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/DamageParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/EndOfTurnParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/StartOfTurnParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/StartTimeParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/TeamParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/WeaponUsedParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/Parsers/WinnerParser.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/Text/ReplayTextReader.cs, CommandLine/src/Worms.Armageddon.Resources/Replays/TurnBuilder.cs, CommandLine/src/Worms.Armageddon.Resources/Schemes/SchemeResource.cs, CommandLine/src/Worms/Cli/CliInfo.cs, CommandLine/src/Worms/Commands/Resources/Process.cs, CommandLine/src/Worms/Commands/Resources/Replays/DeleteReplay.cs, CommandLine/src/Worms/Commands/Resources/Replays/GetReplay.cs, CommandLine/src/Worms/Commands/Resources/Schemes/DeleteScheme.cs, CommandLine/src/Worms/Commands/Resources/Schemes/GetScheme.cs, CommandLine/src/Worms/Commands/Resources/View.cs, CommandLine/src/Worms/Logging/TableOutput/Table.cs, CommandLine/src/Worms/Logging/TableOutput/TableBuilder.cs, CommandLine/src/Worms/Logging/TableOutput/TablePrinter.cs, CommandLine/src/Worms/Resources/Replays/LocalReplayRetriever.cs, CommandLine/src/Worms/Resources/Replays/ReplayTextPrinter.cs
**What**
- Adds more detail to the replay resource. This includes weapons used and damage done.
- Changes the output format of `worms get replay <name>` to show the extracted details rather than the raw log
**New Output**
```
Start Time: 2021-05-19 11.33.17
Teams:
NAME             PLAYER       COLOUR
Cunning Plan     john         Red
Eadie's Army     Eadie        Blue
Eggs Are Cuter   Stephen      Green
Honk             peter        Yellow
Turns:
NUM   TEAM             WEAPONS                             DAMAGE
1     Cunning Plan     Select Worm, Fire Punch             Eadie's Army: 100 (1 kill)
2     Eadie's Army     Bazooka                             Cunning Plan: 45
3     Eggs Are Cuter   Select Worm, Handgun                Honk: 100 (1 kill)
4     Honk             Homing Missile …
```
=> Extract more information from replays

.build/shared/dotnet.sh, .github/workflows/cli.yml, .github/workflows/gif-tool.yml, CommandLine/.build/dockerfile, CommandLine/src/Worms.Armageddon.Game/Modules/WindowsModule.cs, CommandLine/src/Worms.Armageddon.Game/Worms.Armageddon.Game.csproj, CommandLine/src/Worms.Armageddon.Resources.Tests/Worms.Armageddon.Resources.Tests.csproj, CommandLine/src/Worms.Armageddon.Resources/Worms.Armageddon.Resources.csproj, CommandLine/src/Worms.Cli.Resources/Worms.Cli.Resources.csproj, CommandLine/src/Worms/worms.csproj, WormsGifTool/GifTool.Tests/GifTool.Tests.csproj, WormsGifTool/GifTool/GifTool.csproj
Updates all the tools in the repo to .NET 6
=> Update to .NET 6

CommandLine/GitVersion.yml, CommandLine/src/Worms.Armageddon.Files/Schemes/Random/IRandomSchemeGenerator.cs, CommandLine/src/Worms.Armageddon.Files/Schemes/Random/RandomExtensions.cs, CommandLine/src/Worms.Armageddon.Files/Schemes/Random/RandomSchemeGenerator.cs, CommandLine/src/Worms.Cli.Resources/Local/Schemes/LocalSchemeCreateParameters.cs, CommandLine/src/Worms.Cli.Resources/Local/Schemes/LocalSchemeCreateRandomParameters.cs, CommandLine/src/Worms.Cli.Resources/Local/Schemes/LocalSchemeRandomCreator.cs, CommandLine/src/Worms.Cli.Resources/Modules/CliResourcesModule.cs, CommandLine/src/Worms/Commands/Resources/Schemes/CreateScheme.cs
This is an port of (a simplified version of) #33.
~~NB. It changes the short code for resourceFolder to -o over -r as -r is better for random and -o as shorthand for output~~
-> No longer true, removed this as its a larger (breaking) change that turned out to be un-necessary
=> Add random scheme generation

src/cli/src/Worms/Commands/Resources/Games/GetGame.cs, src/cli/src/Worms/Commands/Resources/Replays/GetReplay.cs, src/cli/src/Worms/Commands/Resources/Replays/ProcessReplay.cs, src/cli/src/Worms/Commands/Resources/Schemes/GetScheme.cs, src/cli/src/Worms/Modules/CliModule.cs
=> Allow optional argurments to be optional

src/Worms.Hub.Gateway/API/Controllers/CliFilesController.cs, src/Worms.Hub.Gateway/API/Controllers/GamesController.cs, src/Worms.Hub.Gateway/API/Controllers/ReplaysController.cs, src/Worms.Hub.Gateway/API/Middleware/LoggingMiddleware.cs, src/Worms.Hub.Gateway/Program.cs
EXtract logging of request start/finish to middleware
=> Logging middleware

src/Worms.Cli.Resources/Remote/WormsServerApi.cs
There are some reports of getting 503 Service Unavailible from the Worms Hub server. It might be due to the time taken to spin up the API from a cold start so adding some retry logic to see if that improves things.
=> Retry API calls with exponential backoff

deployment/Worms.Hub.Infrastructure/src/Database.cs
This matches the testing being done
=> Upgrade prod to postgres 15

build/start-azure.sh, deployment/Worms.Hub.Infrastructure/Pulumi.yaml, deployment/Worms.Hub.Infrastructure/src/ContainerApps/Gateway.cs, deployment/Worms.Hub.Infrastructure/src/ContainerApps/ReplayProcessor.cs, deployment/Worms.Hub.Infrastructure/src/Queue.cs, deployment/Worms.Hub.Infrastructure/src/WormsHub.cs, src/Worms.Cli.Resources/Remote/WormsServerApi.cs, src/Worms.Cli/Program.cs, src/Worms.Cli/Worms.Cli.csproj
- Also allows changing the Worms Hub URL used by Worms CLI via environment variable `WORMS_WORMSHUB_URL`
=> Deploy replay processor to Azure

deployment/Worms.Hub.Infrastructure/Worms.Hub.Infrastructure.csproj
=> Update infrastructure to .NET 9

src/Worms.Armageddon.Game/System/Process.cs, src/Worms.Armageddon.Game/Win/WormsRunner.cs
This got broken during the refactoring - ironically to add tests
=> Fix launching Worms when running `worms host` on Windows

.github/workflows/code-branch.yml, .github/workflows/code-main.yml, .github/workflows/schemes.yml
The build has started failing recently due to lack of permissions.
=> Grant write permissions to each workflow

src/Worms.Cli.Resources/Remote/WormsServerApi.cs
=> Await updating game in Hub
